# Generated by Django 3.1.7 on 2021-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210224_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='surname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.CharField(max_length=13),
        ),
    ]
