# Generated by Django 3.1.7 on 2021-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210226_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='static/people'),
        ),
        migrations.AlterField(
            model_name='people',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
