# Generated by Django 3.1.7 on 2021-03-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20210226_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
